#!/usr/bin/env python3


import re
import operator
import csv

error_msg = {} # For Error count
user_entry = {} # For error per user
pattern = re.compile(r"(ERROR|INFO)\s.*\((\w+)")

# This function counts the number of times each error appear in a log
def errorLog():
    with open("syslog.log", "r") as logfile:
        for logline in logfile:
            if "ERROR" in logline:
                match = re.search(r"ERROR\s.*\(", logline)
                match = match.group().strip("(")
                error_msg[match] = error_msg.get(match, 0) + 1
    sorted_mgs = dict(sorted(error_msg.items(), key=operator.itemgetter(1), reverse=True))
    logfile.close()

    # Write to csv file : error_message.csv
    with open("error_message.csv", "w") as csvfile:
        fieldnames = ["ERROR", "COUNT"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        # Loop through the dictionary and write to the csv
        for error, count in sorted_mgs.items():
            writer.writerow({
                "ERROR": error,
                "COUNT": count
            })


# The number of messages generated by each user
def per_user():
    with open("syslog.log", "r") as logfile:
        for logline in logfile:
            match = pattern.search(logline)
            msg_level, user = match.groups()
            user_entry.setdefault(user, {}) # Sets a prototype that our data will be nested dict
            user_entry[user][msg_level] = user_entry[user].get(msg_level, 0) +1
            sorted_entry = dict(sorted(user_entry.items() , key=operator.itemgetter(0)))
    
    # Write to csv file : error_message.csv
    with open("user_statistics.csv", "w") as csvfile:
        fieldnames = ["Username", "Error", "Info"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        # Loop through the dictionary and write to the csv
        for user, count in sorted_entry.items():
                writer.writerow({
                    "Username": user,
                    "Error": count.get("ERROR", 0),
                    "Info": count.get("INFO", 0)
                })
errorLog()
per_user()